import Levenshtein

# Ground truth and OCR text
ground_truth = "Ground truth: information come to our attention, it will be forwarded to addressees. William W. Wells cc: ERDA/ISA/IANA   CENTRAL INTELLIGENCE AGENCY Washington, D.C. 20505 MEMORANDUM FOR: Mr. Martin Dowd, ERDA Division of Safeguards & Security Director Federal Bureau of Investigation Attn: Intelligence Division FROM: William W. Wells Deputy Director for Operations SUBJECT: Alleged Offer for Sale of Uranium and Plutonium REFERENCE: CIA/DDO memorandum dated 10 February 1977, same subject 1. In addition to the report in reference, we have been advised by the source of that information that the composition of the uranium offered for sale by fnu IBGHI is 99.3% of U-238, 0.7% of U-235, and 0.006% of U-234, i.e. natural uranium. The source further reported that the uranium was located in Switzerland, but that four bars of 10kg each have now been shipped to Paris along with 120kg of cobalt. According to the source, IBGHI showed the source two laboratory certifi- cates, one of which was from Lisbon, which guaranteed the genuineness of the uranium and cobalt. 2. Although the source could not report the first name of IBGHI, he described him as an Israeli in his early thirties, about six feet tall, slim and dark haired. 3. In view of the unreliability of the source of this information, it is unlikely that additional information of value can be obtained from him. However, should such  This consist of 2 No. 1 of 2 Copies. Series 55A 6 1 MAR 1977 Sec 9 APPROVED FOR RELEASE Date 30 NOV 1978 AMERICAN REVOLUTION 1776-1976 H-6523 006"
ocr_text = "OCR: CENTRAL INTELLIGENCE AGENCY WASHIGTON.D.C. ZWM 1 i, 1077 9 .Â° p -MEMORANDUM FOR: Mr. Martin Dowd, ERDA Division of Safeguards & Security Director Federal Bureau of Investigation Attn: IntelXigence Division FROM: W lliam W. We eputy Direcforor Operations SUBJECT: Alleged Offer for Sale of Uranium and Plutonium REFERENCE: CIA/DDO memorandum dated 40 February 19 same subject 1. In addition to the report in reference, we have been advised by the source of that information that the compsition of the uranium offered for sale by fnu IBGHI is 99.3% of U-238, 0.7% of U-235, and 0.006% of U-234, i.e. natural uranium. The source further reported that the uranium was located in Switzerlands_but that four bars of 10kg each have now been t'WiThTp-ed to Paris along with 120kg of cobalt. According to the source, IBGHI showed the source two laboratory certifi- cates, one of which was from Lisbon, which guaranteed the genuineness of the uranium and cobalt. 2. Although the source could not report the first name of IBGHI, he described him as an Israeli in his early thirties, about six feet tall, slim and dark haired. 3. In view of the unreliability of the source of this information, it is unlikely that additional information of value can be obtained from him. However, sho suc ~-~Z3004 - -, - q. ' i4 \"i \" iv . *Q information come to our attention, it will be forw.arded to addressees. Wlam W. Wells 9 .L cc: ERDA/ISA/IANA .... -3"

# Calculate the Character Error Rate (CER)
cer = Levenshtein.distance(ground_truth, ocr_text) / len(ground_truth)

# Print the CER
print(f"Character Error Rate (CER): {cer:.4f}")
